### ISSUE TITLE
Try not to use assumingMemoryBound please.

### ISSUE THREAD

**Issue by atrick** [hexdreamer/hidef#1]
`let typedProp = nnprop.assumingMemoryBound(to: propertyType)`

That API is meant for when some other code initialized memory giving it a Swift type, but for some reason passed you a raw pointer and you just happen to know the type anyway. It's always a signal that something is wrong with the design.

To set the initial type of raw memory after allocating it you do:

`let typedProp = nnprop.bindMemory(to: propertyType, capacity: 1)`

That API is meant for exactly your use case where Swift allocates raw bytes without knowing the type, the memory is initialized by a C API, then you need to tell Swift what type is stored there.

You might want to assert somewhere that `MemoryLayout<T>.size == size`.

**Comment by hexdreamer** [comment]
Thanks! Fixed in f2c463f.
